var myRecords = [
  {
    name: "vinyl",
    price: "26",
    description: "Guardians of the Galaxy Deluxe Edition",
    category: "Oldschool",
    id: 1,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81hiw424-sL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91wImk6sZvL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Abbey Road Anniversary",
    category: "Oldschool",
    id: 2,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81dUVKQDBEL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61vrr%2BBVThL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Chronicle: The 20 Greatest Hits",
    category: "Oldschool",
    id: 3,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91ML36Y33TL._SX355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91ml5wOqVHL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Legend",
    category: "Oldschool",
    id: 4,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71EFb-BEAeL._SX355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/A1pQ8niHAbL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Fleetwood Mac: Greatest Hits",
    category: "Oldschool",
    id: 5,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81%2BqJPceY4L._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51iqr6V8TDL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Fine Line",
    category: "Oldschool",
    id: 6,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91SLiiGA4PL._SX355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/A1bdaFpk4UL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Tom Petty & the Heartbreakers - Greatest Hits",
    category: "Oldschool",
    id: 7,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81SF-yIIpiL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61kp6vMIAQL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "The Best of Earth Wind & Fire Vol. 1",
    category: "Oldschool",
    id: 8,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71-Y-3usHkL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71JgN8CZR2L._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "AM",
    category: "hip hop",
    id: 9,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81ESohUha%2BL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/A1xE68W6AVL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Skynyrd's Innyrds: Their Greatest Hits",
    category: "Oldschool",
    id: 10,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/61hw9WloObL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61hw9WloObL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Back to Black",
    category: "Oldschool",
    id: 11,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91jyndgfrEL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/A1bdaFpk4UL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Goodbye Yellow Brick Road Remastered",
    category: "Oldschool",
    id: 12,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/8107M%2B6VbwS._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91XKaVm6OyL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Kind of Blue",
    category: "Oldschool",
    id: 13,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81CP1j-zprL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91DB3TWTfqL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Dirty Dancing Soundtrack",
    category: "Oldschool",
    id: 14,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81Oss0nJkXL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/811TDU4vfQL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Back in Black",
    category: "Oldschool",
    id: 15,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71ZJ8-ByvyL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81Y1i%2BdWpKL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Over It",
    category: "Oldschool",
    id: 16,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71ERmyNKRdL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71ERmyNKRdL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Ready To Die",
    category: "danchall",
    id: 17,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/61aTaJjFrbL._SX522_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61aTaJjFrbL._SX522_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "The Essential Johnny Cash",
    category: "danchall",
    id: 18,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/817VZsCODgL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91wH8WxTh1L._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "PHO",
    category: "danchall",
    id: 19,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/613f%2BJXYT4L._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/613f%2BJXYT4L._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "When It's All Said And Done... ",
    category: "danchall",
    id: 20,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81Wi9Wdk4LL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81so5IHpVkL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Look Up Child",
    category: "danchall",
    id: 21,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71%2BqPvxU78L._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51v9vv1ij%2BL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Halloween Howls: Fun & Scary Music ",
    category: "danchall",
    id: 22,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/61eoFfAK0vL._SX300_SY300_QL70_FMwebp_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71c6ZnEluyL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "All I Know So Far: Setlist",
    category: "danchall",
    id: 23,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/915jqkdJyDL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/915jqkdJyDL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Play Loud",
    category: "danchall",
    id: 24,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/A1W%2BR%2BWUYFL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81We6vWu8pS._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Handle With Care",
    category: "danchall",
    id: 25,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/51f2TaXXL-L._SX300_SY300_QL70_FMwebp_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51f2TaXXL-L._SX300_SY300_QL70_FMwebp_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Play Loud",
    category: "danchall",
    id: 26,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/A1W%2BR%2BWUYFL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81We6vWu8pS._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Mariah Carey",
    category: "danchall",
    id: 27,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71ARLtGozHL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/A1FeeW2LT3L._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "H.E.R.",
    category: "danchall",
    id: 28,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91MlEw58m8L._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91MlEw58m8L._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Weezer Blue Album",
    category: "danchall",
    id: 29,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/61%2BYFnKqzgL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91TeC7SR9JL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Ultimate Sinatra",
    category: "danchall",
    id: 30,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/41WULGxwgEL._SX425_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91s84Ew7p7L._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Rumours (Vinyl 33 & 1/3 RPM)",
    category: "danchall",
    id: 31,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71HWqbh0BLL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51OJvuZLFOL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Welcome 2 America",
    category: "Dub",
    id: 32,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71yGtaOyGeL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/815-x3S0-pL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Winter Wonderland / Various",
    category: "Dub",
    id: 33,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/51iKoA2xIUL._SY300_SX300_QL70_FMwebp_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71FnYh1KvdL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Sound & Fury Black",
    category: "Dub",
    id: 34,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/61qugNE0JqL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71nDMTxzY8L._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Thriller",
    category: "Dub",
    id: 35,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71%2BXneSZL7S._SX355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71P4BnYjXfS._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Gold: Greatest Hits",
    category: "Dub",
    id: 36,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/51zKioWtcdL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81kKy7LfGkL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Chris Tomlin & Friends",
    category: "Dub",
    id: 37,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/B1r6h2%2Bw1MS._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/B1r6h2%2Bw1MS._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Sellout",
    category: "Dub",
    id: 38,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81Q5zJwzaRL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81Q5zJwzaRL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Chris Tomlin & Friends",
    category: "Dub",
    id: 39,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/B1HhoylfabS._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/B1r6h2%2Bw1MS._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "70s: The Songs / Various",
    category: "Dub",
    id: 40,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81Q5zJwzaRL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91fCb1qOSoL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Back from the Edge",
    category: "Dub",
    id: 41,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71B-bnKFQZL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71B-bnKFQZL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "70s: The Songs / Various",
    category: "Dub",
    id: 42,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81Q5zJwzaRL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91fCb1qOSoL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Cuz I Love You Deluxe",
    category: "Dub",
    id: 43,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/51pwa8dSpcL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51DvajQB%2BUL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Their Greatest Hits 1971-1975",
    category: "Dub",
    id: 44,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/A1paB3RNigL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51v%2BTmTWDeL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Greatest Hits I",
    category: "Dub",
    id: 45,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/8104ss9V1-L._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91Ng2iiPeXL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Ultimate Christmas",
    category: "Dub",
    id: 46,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/61YXGdRp0lL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51MBP7pWKeL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "By and By",
    category: "Roots",
    id: 47,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81BObf%2BKihL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81BObf%2BKihL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Greatest Hits",
    category: "Roots",
    id: 48,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81JaN02Ud6L._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91lTopXEvfL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Legends Never Die",
    category: "Roots",
    id: 49,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/A1ig9xV8RpL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71wLgvouThL._SX466_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Black Sabbath",
    category: "Roots",
    id: 50,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/714KHDRE69S._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/61oHmYJgx-L._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "The Best Of Trojan Roots ",
    category: "Roots",
    id: 51,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91pAlXO5IQL._SX450_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/914p%2BlAUR0L._SX450_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Rocking Vibration",
    category: "Roots",
    id: 52,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91Q5Eo6-tJL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/B1-wovP1WbS._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Live At The Rainbow",
    category: "Roots",
    id: 53,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81cXG%2Bdhi1L._SX522_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71YIWKZ0kdL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Marcus Garvey",
    category: "Roots",
    id: 54,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71cqpP0mjYS._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81PXfPURubL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Peter Tosh",
    category: "Roots",
    id: 55,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91n9wMEmrFL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81ySRzg7aAL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Same Song",
    category: "Roots",
    id: 56,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91OWtiU1kIL._SY355_.jpg ",
      "https://images-na.ssl-images-amazon.com/images/I/61ufuEXOs1L._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Soul Pirate",
    category: "Roots",
    id: 57,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/71CwmcRajsL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71Yz1qr6D9L._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Studio One Roots, Vol. 2",
    category: "Roots",
    id: 58,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/91RVv1hO4LL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91tGtDRS4lL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Iimini",
    category: "Roots",
    id: 59,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/61HvL2YXfsL._SX425_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71hrDcXOfLL._SY355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Hell a Go Pop",
    category: "Roots",
    id: 60,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/61-WYiURfbL._SY355_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81q7iEwJprL._SX355_.jpg",
    ],
  },
  {
    name: "vinyl",
    price: "26",
    description: "Live At The Rainbow: 4th June 1977",
    category: "Roots",
    id: 51,
    picture: [
      "https://images-na.ssl-images-amazon.com/images/I/81cXG%2Bdhi1L._SX522_.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/71YIWKZ0kdL._SY355_.jpg",
    ],
  },
];
